# -*- Mode: makefile-gmake -*-

EXE = test_logger

COMMON_SRC = dbuslog_category.c dbuslog_message.c
CLIENT_SRC = dbuslog_receiver.c
SERVER_SRC = dbuslog_core.c dbuslog_sender.c

include ../common/Makefile
